name = "Sosiski-3"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a62a19283a0f3b22473f9cf8dd5259d1ada4a4bc47a68cc2b20b12486cd85d02"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
