name = "Sosiski-3"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2c6ead9365fcef48231368bd05ff64f01350da7d5e153b75f30d1179b7c2991"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
