name = "Sosiski-3"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c795f090ab194846b287883044ca5cc7c0298fc763cad007e96dbbc8c81ea2af"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
